import type { Metadata } from "next";
import { LegalPage, LegalSection } from "@/components/LegalPage";
import { BRAND } from "@/lib/config";

export const metadata: Metadata = {
  title: "Terms",
  description: "Terms of use for mSport.",
};

export default function TermsPage() {
  return (
    <LegalPage title="Terms" updated="August 2026">
      <LegalSection heading="What mSport is">
        <p>
          {BRAND.name} is an analysis tool. It reads material you supply and produces a structured
          reading of it. It is not a news source, a wire service, a sportsbook, a fantasy platform,
          or a substitute for reporting.
        </p>
      </LegalSection>

      <LegalSection heading="Verify before you publish">
        <p>
          Output is generated by an AI model and can be wrong. Every Anatomy marks what the supplied
          material supports and what it doesn&apos;t, and lists claims that need checking — those
          sections exist because they matter.
        </p>
        <p>
          If you publish, broadcast or post anything derived from mSport, you are responsible for
          verifying it. Treat the output as a research pass, not a source.
        </p>
      </LegalSection>

      <LegalSection heading="Your material">
        <p>
          You keep whatever rights you have in the material you submit and in the output you get
          back. Only submit material you have the right to use. Don&apos;t submit content that
          infringes someone else&apos;s rights, and don&apos;t use a link to route around a
          paywall.
        </p>
      </LegalSection>

      <LegalSection heading="Acceptable use">
        <p>
          Don&apos;t use mSport to generate betting or gambling advice, to impersonate a publication
          or a person, to produce content presented as first-hand reporting when it isn&apos;t, or
          to attempt to overload or probe the service.
        </p>
      </LegalSection>

      <LegalSection heading="Free trial and payments">
        <p>
          The free trial is offered as-is and may change. Paid packs are not available yet; no
          payment is being taken and no payment obligation exists. Prices shown for future packs are
          indicative and may change before launch.
        </p>
      </LegalSection>

      <LegalSection heading="Availability">
        <p>
          mSport is early software provided without warranty. It may be unavailable, may change, and
          may fail on material it can&apos;t read. To the extent permitted by law, we&apos;re not
          liable for losses arising from use of the service or reliance on its output.
        </p>
      </LegalSection>
    </LegalPage>
  );
}
